config/routes.rb
Rails.application.routes.draw do

  root "users#index"
  
  resources :users, except: [:destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]

  get "sign_up"=> "users#new"
  get "log_in" => "sessions#new"
  get "log_out" => "sessions#destroy"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  validates :text, :user, presence: true 
end

app/models/user.rb
require "openssl"
class User < ApplicationRecord

    ITERATIONS = 20000
    DIGEST = OpenSSL::Digest::SHA256.new
    
    has_many :questions, dependent: :destroy
    validates :email, :username, presence: true 
    validates :email, :username, uniqueness: true 

    attr_accessor :password
    validates_presence_of :password, on: :create
    validates_confirmation_of :password

    before_save :encrypt_password

    def encrypt_password
        if self.password.present?
            self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

            self.password_hash = User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(
                self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST)
                )
        end
    end
    def self.hash_to_string(password_hash)
        password_hash.unpack('H*')[0]
    end
    def self.authenticate(email, password)
        user = find_by(email: email)

        if user.present? && user.password_hash == User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(
                password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
                user
        else
            nil
        end           
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_url, alert: "You cannot edit someone else`s profile!"
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [ :show, :edit, :update, :destroy ]
  before_action :authorize_user, except: [ :create ]
  
  def edit
  end

  def show
  end

  def create
    @question = Question.new(question_params)
      if @question.save
        redirect_to user_path(@question.user), notice: "Question was successfully created." 
      else
        render :new, status: :unprocessable_entity
      end
  end


  def update
      if @question.update(question_params)
        redirect_to user_path(@question.user), notice: "Question was successfully updated."
      else
        render :edit
      end
  end

  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(user), notice: "Question was successfully destroyed."
  end

  private
    def load_question
      @question = Question.find(params[:id])
    end

    def authorize_user
      reject_user unless @question.user == current_user
    end

    def question_params
      if current_user.present? && params[:question][:user_id].to_i == current_user.id
        params.require(:question).permit(:user_id, :text, :answer)
      else
        params.require(:question).permit(:user_id, :text)
      end
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user.present?
      session[:user_id] = @user.id
      redirect_to root_url, notice: "You have successfully logged in!"
    else
      flash.now.alert = "Incorrect email or password!" 
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You have been logged out of your account."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_user, except: [ :index, :new, :create ]
  before_action :authorize_user, except: [ :index, :new, :create, :show ] 

  def index
    @users = User.all
  end

  def new
    redirect_to root_url, alert: "You are already logged in" if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_url, alert: "You are already logged in" if current_user.present?
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: "User successfully created!"
    else
      render :new, status: :unprocessable_entity
    end

  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have successfully updated your profile."
    else
      render :edit, status: :unprocessable_entity
    end
  end
  

def show
  @questions = @user.questions.order(created_at: :desc)
  @new_question = @user.questions.build
end

  private
  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :username, :avatar_url, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def user_avatar(user)
      if user.avatar_url.present?
        user.avatar_url
      else
          asset_path "avatar.png"
      end
    end
    def user_bio(user)
      if user.bio.present?
      user.bio
      else
      "#{user.name} hasn't written anything yet"
      end
    end

    def fa_icon(icon_class)
      content_tag "span", "", class: "fa fa-#{icon_class}" 

    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <title><%= content_for(:title) || "TWIDY App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"/>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <aside class="header">
      <div class="logo">
        <%= image_tag "logo.png"%>
        <%= link_to "", root_path %>
      </div>
      <nav class="header-nav">
        
          <div class="nav-item"><%= image_tag "header-home.svg"%><%= link_to "Main Page", root_path, class: "nav-link"%></div>
          <div class="nav-item"><%= image_tag "header-message.svg"%><%= link_to "My Questions", root_path, class: "nav-link" %></div>
          <% if current_user == @user  %>
            <div class="nav-item">
              <%= image_tag "header-settings.svg"%>
              <%= link_to "Settings", edit_user_path(@user), class: "nav-link"  %>
            </div>
          <% end %>
        </ul>
      </nav>
    </aside>

    <div class="content">
      <header>
        <input type="search" placeholder="Search..." class="search-input" />
        <div class="button-group">
          <%if current_user%>
            <%= link_to user_path(current_user), class: "profile-link" do %>
            <div class="profile-wrapper">
              <%= image_tag current_user.avatar_url, alt: "#{current_user.username}'s avatar", class: "user-image-t" if current_user.avatar_url.present? %>
              <span class="green-dot"></span>
              </div>
              @<%= current_user.username %>
            <% end %>
            <%= link_to "Logout", log_out_path, class: "link" %>
          <%else%>
            <%= link_to "Register", sign_up_path, class: "btn register-btn" %>
            <%= link_to "Login", log_in_path, class: "btn login-btn" %>
          <%end%>  
        </div>
      </header>
      <main>
        <% if flash.any?%>
          <div class="flash-wrapper">
            <% flash.each do |name, message|%>
              <%= content_tag :div, message, class: "flash-#{name}"%>
            <%end%>  
          </div>
        <%end%>  
        <%= yield %>
      </main>
    </div>
    
  </body>
</html>

app/views/questions/_form.html.erb
<div class="form">
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div class="form-errors">
      <ul>
        <% @question.errors.full_messages.each do |message| %>
          <li class="form-errors-message"><%= message %></li>
        <% end %> 
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :user_id%> 
  <div class="new-form-field">
    <%= f.label :text, 'Question', class: "form-label" %>
    <%= f.text_area :text, readonly: true, class: "form-textarea" %>
  </div>
  <% if current_user.present? && current_user == @question.user %>
  <div class="new-form-field">
    <%= f.label :answer, 'Answer', class: "form-label" %>
    <%= f.text_area :answer, class: "form-textarea" %>
  </div>
  <% end %>
  <div class="form-action">
    <%= f.submit "Save", class: "button" %>
    or 
    <%= link_to "return", user_path(@question.user) %>
  </div>
<% end %>
</div>

app/views/questions/_question.html.erb
<% question ||= nil %>
<% action_icon = question.answer.blank? ? "reply" : "pencil" %>

<div class="question">
    <div class="question-content">
        <div class="question-text">
            <%= question.text %>
        </div>
        <% if question.answer.present? %>
            <div class="question-answer">
                <%= question.answer if question.answer.present? %>
            </div>
        <%end%>
        <div class="question-bottom">
            <div class="question-date">
            <%= l(question.created_at, format: :short) %>
            </div>
            <% if question.user == current_user%>
            <div class="question-actions">
                <%= link_to fa_icon(action_icon), edit_question_path(question) %>
                <%= link_to fa_icon("trash-o"), question_path(question), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this question?" } %>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/questions/edit.html.erb
<div class="new-form">
    <h1 class="new-title">Answer question here</h1>
    <div>
      <%= render 'form' %>
    </div>
</div>

app/views/users/edit.html.erb
<div class="new-form">
    <h1 class="new-title">Edit your profile</h1>
  <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-errors-message"><%= message %></li>
            <% end %> 
          </ul>
        </div>
      <% end %>  
    <div class="new-form-field">
      <%= f.label :username, "Username", class: "new-form-label" %>
      <%= f.text_field :username, class: "form-input" %>
    </div>

    <div class="new-form-field">
      <%= f.label :name, "Name", class: "new-form-label" %>
      <%= f.text_field :name, class: "form-input" %>
    </div>

    <div class="new-form-field">
      <%= f.label :bio, "Write about yourself", class: "new-form-label" %>
      <%= f.text_field :bio, class: "form-input" %>
    </div>

        <div class="new-form-field">
      <%= f.label :avatar_url, "Your photo (URL)", class: "new-form-label" %>
      <%= f.text_field :avatar_url, class: "form-input" %>
    </div>

    <h5>If you do not want to change your password, leave these fields blank!</h5>

    <div class="new-form-field">
      <%= f.label :password, "Password", class: "new-form-label" %>
      <%= f.password_field :password, class: "form-input" %>
    </div>

    <div class="new-form-field">
      <%= f.label :password_confirmation, "Password Confirmation", class: "new-form-label" %>
      <%= f.password_field :password_confirmation, class: "form-input" %>
    </div>

    <div class="new-form-action">
      <%= f.submit "Save the changes", class: "button" %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="content-wrapper">
    <div class="buffer-both">
        <h1 class="title">Our Users</h1>
    </div>
    <div class="user-wrapper">
    <% @users.each do |user|%>
    <div class="user-list-item">
        <div class="user-image-preview">
            <%= link_to image_tag(user_avatar(user), class: "user-image-s"), user_path(user) %>
        </div>
    </div>
    <% end %>
    </div>
</div>

app/views/users/new.html.erb
<div class="new-form">
    <h1 class="new-title">Join us!</h1>
  <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-errors-message"><%= message %></li>
            <% end %> 
          </ul>
        </div>
      <% end %>  
    <div class="new-form-field">
      <%= f.label :email, "Email", class: "new-form-label" %>
      <%= f.email_field :email, required: true, class: "form-input" %>
    </div>

    <div class="new-form-field">
      <%= f.label :username, "Username", class: "new-form-label" %>
      <%= f.text_field :username, required: true, class: "form-input" %>
    </div>

    <div class="new-form-field">
      <%= f.label :name, "Name", class: "new-form-label" %>
      <%= f.text_field :name, required: true, class: "form-input" %>
    </div>

    <div class="new-form-field">
      <%= f.label :password, "Password", class: "new-form-label" %>
      <%= f.password_field :password, required: true, class: "form-input" %>
    </div>

    <div class="new-form-field">
      <%= f.label :password_confirmation, "Password Confirmation", class: "new-form-label" %>
      <%= f.password_field :password_confirmation, required: true, class: "form-input" %>
    </div>

    <div class="new-form-action">
      <%= f.submit "Create an account", class: "button" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-container">
    <div  class="user-card">
        <h2 class="title">@<%= @user.username %></h2>
        <div class="user-card_bio">
            <div class="user-img-container">
                <%= image_tag user_avatar(@user), alt: 'profile pic', class: "image" %>
            </div>
            <h3 class="user-subtitle">Name: <%= @user.name %></h3>
            <h3 class="user-subtitle">Bio: <%= user_bio(@user)%></h3>
            <%# <div class="user-edit">
                <%= link_to "Edit profile", edit_user_path(@user), class: "user-edit-link" if current_user == @user %>
            <%# </div> %> 
            <a href="#" class="button button-mobile" id="ask-button">Ask question</a>
        </div>
    </div>
    <div class="user-question-form" id="ask-form">
        <div class="form">
            <%= form_for @new_question do |f| %>
                <%= f.hidden_field :user_id%>
                    <div class="form-field">
                        <%= f.label "Ask @#{@user.username} about anything!", class: "form-label"%>
                        <%= f.text_area :text, class: "form-textarea" %>
                    </div>
                <div class="form-action"> 
                    <%= submit_tag "Ask question", class: "button" %>
                </div>
            <% end %>
            <div class="question-block">
                <h2 class="title">Questions</h2>
                <div class="question-wrapper">
                    <% @questions.each do |question| %>
                        <%= render partial: 'questions/question', object: question %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>


            
            